### ISSUE TITLE
[Feature]: ゲームモードと難易度のtooltip用テキストを決定する

### ISSUE THREAD

**Issue by waonpad** [waonpad/miraisozoten#171]
### 機能の要約

モードと難易度については、tooltipでどのようなシステムかを知れるようにする予定である

ユーザーが理解しやすいテキストが求められる

### 利益・価値

モードと難易度について、ユーザーがすぐに内容を理解出来る

**Comment by sT507** [comment]
インフォメーション用テキストです。↓↓↓


【難易度】
バトル難易度を設定します。
Easy：3選択肢から対戦要素を選びます。
Normal：4選択肢から対戦要素を選びます。
Hard：6選択肢から対戦要素を選びます。
Very Hard：6選択肢に加え、データの数値を見ることができません。

【モード】
バトル時のモードを設定します。
地方制覇モード：選択した都道府県の所属する地方の都道府県と闘います。手軽に遊びたい方におすすめです。
全国制覇モード：選択した都道府県で全国の都道府県と闘います。対戦数が多いため、集中して遊びたい方におすすめです。

**Comment by waonpad** [comment]
Hard: 4択で数値みえない
